name: Test

on:
  pull_request:
  push:
    branches:
      - primary

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
  integrationTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          check: npm run format-check
          format: npm run format
          token: ${{ github.token }}
